# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: truffle compile
          command: |
            sudo npm install -g truffle@4.1.3
            truffle compile
      - run:
          name: test
          command: npm test
      - run:
          name: build
          command: |
            sudo npm install -g grunt
            grunt
      - run:
          name: install flattener
          command: npm install truffle-flattener
      - run:
          name: flatten contract
          command: |
            node node_modules/truffle-flattener/index.js contracts/Fee.sol > Fee.txt
            node node_modules/truffle-flattener/index.js contracts/Stake.sol > Stake.txt
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker image
          command: |
            docker info
            docker build -t leverj/stake:$CIRCLE_BRANCH .
            docker build -f Dockerfile-automation -t leverj/stake-automation:$CIRCLE_BRANCH .
            docker build -f Dockerfile-contract-deploy -t leverj/stake-contract:$CIRCLE_BRANCH .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push leverj/stake
            docker push leverj/stake-automation
            docker push leverj/stake-contract

